port: 7890
socks-port: 7891
mode: rule
log-level: info #在调试结果后，改为error或warn，减少日志输出。
allow-lan: true
external-controller: '0.0.0.0:9090'
external-ui: /usr/local/etc/mihomo/ui
secret: 123456
tun:
  enable: true
  stack: gvisor #使用gvisor栈，提供更好的兼容性和性能，system栈可能在某些环境下存在兼容性问题。
  device: tun_3000
  mtu: 9000
  auto-route: true  # ❌ 关键：关闭自动路由，由OPNsense系统管理
  strict-route: true  # ❌ 关键：关闭严格路由，避免冲突
  auto-detect-interface: true  # ❌ 关键：关闭自动检测，手动指定
  dns-hijack:
    - any:53
    - tcp://any:53
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: whitelist
  fake-ip-filter:
    - '*.lan'
    - 'localhost'
    - '10.0.0.0/24' # ✅ 保留内网IP不走代理
  listen: 0.0.0.0:7853
  default-nameserver: 
    - 127.0.0.1:5335 # 指向mosdns
  nameserver:
    - 127.0.0.1:5335
