[start]
command:sh /usr/local/etc/rc.d/mihomo start
parameters:
type:script
message:starting mihomo 

[stop]
command:sh /usr/local/etc/rc.d/mihomo stop
parameters:
type:script
message:stopping mihomo 

[restart]
command:sh /usr/local/etc/rc.d/mihomo restart
parameters:
type:script
message:restarting mihomo 
description:Restart mihomo service

[status]
command:sh /usr/local/etc/rc.d/mihomo status;exit 0
parameters:
type:script_output
message:request mihomo status

[sub-update]
command:/usr/bin/sub
parameter:
type:script_output
description:Renew mihomo Subscription