log:
  level: error  # 🔥 这里从 warn 改为 error，屏蔽所有无害警告
  production: true
  file: "/var/log/mosdns.log" 

api:
  http: "127.0.0.1:9091" 

plugins:
  - tag: "cache_0"
    type: cache
    args:
      size: 4194304
      lazy_cache_ttl: 3600 
      dump_file: /var/db/mosdns.cache
      dump_interval: 7200

  - tag: "reverse_lookup"
    type: reverse_lookup
    args:
      size: 5000
      ttl: 14400
      handle_ptr: true

  - tag: "remote_domain_set"
    type: domain_set
    args:
      files:
        - "/usr/local/etc/mosdns/rule/gfw.txt"
        - "/usr/local/etc/mosdns/rule/proxy-list.txt"

  - tag: "direct_domain_set"
    type: domain_set
    args:
      files:
        - "/usr/local/etc/mosdns/rule/direct-list.txt"

  - tag: "direct_ip"
    type: ip_set
    args:
      files:
        - "/usr/local/etc/mosdns/rule/all_cn.txt"

  - tag: "remote_forward"
    type: forward
    args:
      upstreams:
        - tag: dnscrypt_plugin_udp
          addr: "udp://127.0.0.1:5353"
          enable_pipeline: true
          idle_timeout: 15 

  - tag: "domestic_forward"
    type: forward
    args:
      upstreams:
        - tag: dnspod_doh
          addr: "https://doh.pub/dns-query"
          enable_pipeline: true
          idle_timeout: 10

  - tag: "ttl_sequence"
    type: sequence
    args:
      - exec: ttl 600-86400
      - exec: accept

  - tag: "domestic_sequence"
    type: sequence
    args:
      - exec: $domestic_forward
      - exec: goto ttl_sequence

  - tag: "remote_sequence"
    type: sequence
    args:
      - exec: $remote_forward
      - exec: goto ttl_sequence

  - tag: "fallback"
    type: fallback
    args:
      primary: remote_sequence
      secondary: remote_sequence
      threshold: 1800
      always_standby: false

  - tag: "main"
    type: sequence
    args:
      - exec: prefer_ipv4
      - exec: $cache_0
      - matches: has_resp
        exec: accept
      - exec: $reverse_lookup
      - matches: has_resp
        exec: accept
      - matches: "qname $remote_domain_set"
        exec: goto remote_sequence
      - matches: "qname $direct_domain_set"
        exec: goto domestic_sequence
      - exec: $fallback
      
  - tag: udp_server
    type: udp_server
    args:
      entry: main
      listen: "127.0.0.1:5335"

  - tag: tcp_server
    type: tcp_server
    args:
      entry: main
      listen: "127.0.0.1:5335"
      idle_timeout: 10

  - tag: "http_server"
    type: "http_server"
    args:
      entries:
        - path: /dns-query
          exec: main
      src_ip_header: "X-Forwarded-For"
      listen: 127.0.0.1:5443
      idle_timeout: 30