# ==================== 基础配置 ====================
port: 7890
socks-port: 7891
mode: rule
log-level: info                     # 调试时改为 debug，稳定后改 error/warn
external-controller: 0.0.0.0:9090
external-ui: /usr/local/etc/clash/ui
secret: 123456

# ==================== TUN 模式（启用 DNS 劫持） ====================
tun:
  enable: true
  stack: system
  device: tun_3000
  mtu: 9000
  auto-route: true
  strict-route: true               # 避免路由卡死，必须 false
  auto-detect-interface: true
  dns-hijack:                       # 劫持所有 53 端口 DNS 请求
    - any:53
    - tcp://any:53

# ==================== DNS 配置 ====================
dns:
  enable: true
  listen: 0.0.0.0:7853              # Clash 内部 DNS 端口，不占用 53
  enhanced-mode: fake-ip    
  respect-rules: true               # DNS 查询遵守规则（用于解析 fallback 中的 DoH 域名）
  use-hosts: true
  use-system-hosts: true
  proxy-server-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - 127.0.0.1:5335                # MosDNS 监听地址

  fallback:
    - 127.0.0.1:5335
    #- https://cloudflare-dns.com/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4

  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
# ==================== 流量嗅探 ====================
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "+.push.apple.com"


